# Generated by Django 5.2.15 on 2026-06-09 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject_line', models.CharField(blank=True, max_length=998)),
                ('context', models.TextField(blank=True, help_text='Product, offer, audience, and key message for the email.')),
                ('style_guidelines', models.TextField(blank=True, help_text='Brand colors, tone, layout preferences.')),
                ('html_content', models.TextField(blank=True)),
                ('image_assets', models.JSONField(blank=True, default=list, help_text='List of {id, alt_text, data_url} image references.')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('generated', 'Generiert')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_projects', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'title'), name='email_marketing_unique_project_title_per_org')],
            },
        ),
    ]
