# Generated by Django 5.2.15 on 2026-06-13 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('local', 'Lokal')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('key_prefix', models.CharField(blank=True, max_length=12)),
                ('key_last4', models.CharField(blank=True, max_length=8)),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_credentials', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_credentials', to='organizations.organization')),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider'), name='uniq_org_ai_provider')],
            },
        ),
        migrations.CreateModel(
            name='ModuleAIBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_slug', models.SlugField(max_length=120)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('local', 'Lokal')], max_length=30)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_ai_bindings', to='organizations.organization')),
            ],
            options={
                'ordering': ['module_slug'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'module_slug'), name='uniq_org_module_ai_binding')],
            },
        ),
    ]
