# Generated by Django 5.2.15 on 2026-06-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userdashboardwidget_unique_user_org_widget_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdashboardwidget',
            name='unique_user_org_widget',
        ),
        migrations.AddConstraint(
            model_name='userdashboardwidget',
            constraint=models.UniqueConstraint(condition=models.Q(('widget_type', 'platform.empty'), _negated=True), fields=('user', 'organization', 'widget_type'), name='unique_user_org_widget'),
        ),
    ]
